### ISSUE TITLE
Too much privilege

### ISSUE THREAD

**Issue by antoinetran** [moosefs/moosefs-docker-cluster#4]
All containers in docker-compose.yml have `privileged: true` but they shouldn't because this is a bad practice. In fact, only MooseFs client needs some kind of privilege:
```
mfsclient:
    image: moosefs/client  #use GitHub version
    #build: ./moosefs-client  #use local version
    cap_add:
      # Needed for mount.
      - SYS_ADMIN
```

We have for months such a configuration and it works well (in CentOs base image).

**Comment by karolmajek** [comment]
You are right, thanks!
Was able to run it using:
```
    cap_add:
      # Needed for mount.
      - SYS_ADMIN
    devices:
      # Needed for mount.
      - /dev/fuse:/dev/fuse
    security_opt:
      # Needed for mount.
      - apparmor:unconfined
```
